// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:absensi_app/core/constants/app_constants.dart';
import 'package:absensi_app/data/models/attendance_model.dart';
import 'package:absensi_app/data/models/leave_model.dart';
import 'package:absensi_app/data/models/overtime_model.dart';
import 'package:absensi_app/data/models/shift_assignment_model.dart';
import 'package:absensi_app/data/models/shift_model.dart';
import 'package:absensi_app/data/models/site_model.dart';
import 'package:absensi_app/data/models/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceModelAdapter());
    registerAdapter(AttendanceStatusAdapter());
    registerAdapter(LeaveModelAdapter());
    registerAdapter(LeaveStatusAdapter());
    registerAdapter(OvertimeModelAdapter());
    registerAdapter(OvertimeStatusAdapter());
    registerAdapter(ShiftAssignmentModelAdapter());
    registerAdapter(ShiftModelAdapter());
    registerAdapter(SiteModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceModelAdapter());
    registerAdapter(AttendanceStatusAdapter());
    registerAdapter(LeaveModelAdapter());
    registerAdapter(LeaveStatusAdapter());
    registerAdapter(OvertimeModelAdapter());
    registerAdapter(OvertimeStatusAdapter());
    registerAdapter(ShiftAssignmentModelAdapter());
    registerAdapter(ShiftModelAdapter());
    registerAdapter(SiteModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
